export const HELLO = "Hello👋,";
export const BALANCE = "Balance";
export const TODAY_SPENDS = "Today Spends";
export const TODAY_LIMIT = "Today Limit ";
export const TODAY_STATISTICS = "Today Statistics";
export const SAVINGS = "Savings";
export const SPEND_AMOUNT = "Spend Amount"
export const UPDATE = "Update"
export const SPENDS = "Spends"
export const LIMIT = "Limit"
export const SET_MONTHLY_AMOUNT = "Please enter amount"
export const MONTHLY_AMOUNT_ZERO_DISC = "Your monthly limit is currently set to zero. Please configure your monthly amount.";
