export const HELLO = "Hello👋,";
export const BALANCE = "Balance";
export const TODAY_SPENDS = "Today Spends";
export const TODAY_LIMIT = "Today Limit ";
export const TODAY_STATISTICS = "Today Statistics";
export const SAVINGS = "Savings";
export const SPEND_AMOUNT = "Spend Amount"
export const UPDATE = "Update"
export const SPENDS = "Spends"
export const LIMIT = "Limit"